// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADO1CV7lulvmQWDeBKengiXFvjonGZ3i8',
    appId: '1:647725016962:web:e6c80381434451ad35119b',
    messagingSenderId: '647725016962',
    projectId: 'pi3-g37',
    authDomain: 'pi3-g37.firebaseapp.com',
    storageBucket: 'pi3-g37.firebasestorage.app',
    measurementId: 'G-68PR2GGRR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtpCca0kPHfNJ3ZQvt4gcB1uBu5L-kdH0',
    appId: '1:647725016962:android:efc8809101e50b9235119b',
    messagingSenderId: '647725016962',
    projectId: 'pi3-g37',
    storageBucket: 'pi3-g37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIGeFIjuO6m3nN49d9693xjKIB4VN1ee4',
    appId: '1:647725016962:ios:3166df58f42b2a7e35119b',
    messagingSenderId: '647725016962',
    projectId: 'pi3-g37',
    storageBucket: 'pi3-g37.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );
}
